name       : pcsxr
version    : 1.9.93
release    : 3
source     :
    - https://sources.archlinux.org/other/community/pcsxr/pcsxr-1.9.93.tar.bz2 : 4d114bb8cd6a278d28c35020d62b928be4be7d6a1d45d7da3c808e4a4681fd9d
license    : GPL-2.0-or-later
component  : games.emulator
summary    : PlayStation emulator
description: |
    PCSX-Reloaded is a PlayStation emulator based on PCSX-df 1.9, with many bugfixes and improvements.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcdio)
    - pkgconfig(libpulse)
    - pkgconfig(openal)
    - pkgconfig(sdl)
    - pkgconfig(xxf86vm)
    - pkgconfig(xtst)
    - pkgconfig(xv)
setup      : |
    %patch -p1 < $pkgfiles/0002-clean-library-install-path.patch
    %patch -p1 < $pkgfiles/pcsxr-1.9.94-zlib129fix.patch
    %autogen --enable-opengl
build      : |
    %make
install    : |
    %make_install
