name       : pcsxr
version    : 1.9.93
release    : 1
source     :
    - http://download-codeplex.sec.s-msft.com/Download/Release?ProjectName=pcsxr&DownloadId=722114&FileTime=130220301656670000&Build=21031 : 4d114bb8cd6a278d28c35020d62b928be4be7d6a1d45d7da3c808e4a4681fd9d
license    : GPL-2.0
component  : games.emulator
summary    : PlayStation emulator
description: |
    PCSX-Reloaded is a PlayStation emulator based on PCSX-df 1.9, with many bugfixes and improvements.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcdio)
    - pkgconfig(libpulse)
    - pkgconfig(openal)
    - pkgconfig(sdl)
    - pkgconfig(xtst)
    - pkgconfig(xv)
setup      : |
    %patch -p1 < $pkgfiles/0002-clean-library-install-path.patch
    %autogen
build      : |
    %make
install    : |
    %make_install
