name       : pcsxr
version    : 1.9.95
release    : 4
source     :
    - https://github.com/frealgagu/archlinux.pcsxr/releases/download/1.9.95-2/pcsxr-1.9.95.tar.gz : 1a132bf4d1875cd2ab90b335620659caa1af2056e7c3d622fb438a0fa90d948d
license    : GPL-2.0-or-later
component  : games.emulator
summary    : PlayStation emulator
description: |
    PCSX-Reloaded is a PlayStation emulator based on PCSX-df 1.9, with many bugfixes and improvements.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcdio)
    - pkgconfig(libpulse)
    - pkgconfig(openal)
    - pkgconfig(sdl)
    - pkgconfig(xxf86vm)
    - pkgconfig(xtst)
    - pkgconfig(xv)
environment: |
    export CFLAGS="${CFLAGS} -fcommon"
setup      : |
    %patch -p1 < $pkgfiles/pcsxr-fix-undefined-operations.patch
    %patch -p1 < $pkgfiles/pcsxr-remove-assertion-64bit.patch
    %patch -p1 < $pkgfiles/pcsxr-fix-uncompress2.patch
    pushd pcsxr
    %patch -p1 < $pkgfiles/0001-Do-not-use-games-dir-at-all.patch
    chmod +x autogen.sh
    %autogen --enable-opengl
build      : |
    pushd pcsxr
    %make
install    : |
    pushd pcsxr
    %make_install
